Args = --no-fallback \
       --features=clj_easy.graal_build_time.InitClojureClasses \
       --install-exit-handlers \
       -H:+UnlockExperimentalVMOptions \
       -H:+ReportExceptionStackTraces \
       -H:+TrackPrimitiveValues \
       -H:+UsePredicates \
       -Os \
       --initialize-at-build-time=org.fusesource.jansi.Ansi$Attribute \
       --initialize-at-build-time=org.fusesource.jansi.Ansi$Color \
       --initialize-at-build-time=org.eclipse.aether.transport.http.HttpTransporterFactory
