name: Publish kmono 👘
on: [push]

jobs:
  build-and-publish:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    env:
      GITHUB_USERNAME: ${{ secrets.ORG_GITHUB_ACTOR }}
      GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: extractions/setup-just@v1

      - uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: latest

      - uses: s4u/maven-settings-action@v2.4.1
        with:
          githubServer: false
          servers: |
            [{"id": "github-kepler",
              "username": "${{ secrets.ORG_GITHUB_ACTOR }}",
              "password": "${{ secrets.ORG_GITHUB_TOKEN }}"},
             {"id": "github-kepler-kmono",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"}]

      # - name: Test
      #   run: |
      #     just test ":snapshot?" ${{ github.ref_name != 'master' }}

      - name: Build
        run: |
          just build ":snapshot?" ${{ github.ref_name != 'master' }}

      - name: Release
        run: |
          just release \
            ":snapshot?" ${{ github.ref_name != 'master' }} \
            ":create-tags?" ${{ github.ref_name == 'master' }}

